export const SEARCH_RESULTS_REQUEST = 'SEARCH_RESULTS_REQUEST'
export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS'
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE'
export const SEARCH_RESULTS_SELECT = 'SEARCH_RESULTS_SELECT'
export const SEARCH_RESULTS_UNSELECT = 'SEARCH_RESULTS_UNSELECT'

export const JOBS_REQUEST = 'JOBS_REQUEST'
export const JOBS_SUCCESS = 'JOBS_SUCCESS'
export const JOBS_FAILURE = 'JOBS_FAILURE'
export const JOBS_SELECT_JOB = 'JOBS_SELECT_JOB'


export const SCHEDULE_REQUEST = 'SCHEDULE_REQUEST'
export const SCHEDULE_SUCCESS = 'SCHEDULE_SUCCESS'
export const SCHEDULE_FAILURE = 'SCHEDULE_FAILURE'


export const PLAYER_IS_PLAYING = 'PLAYER_IS_PLAYING'
export const PLAYER_UPDATE_VIDEO = 'PLAYER_UPDATE_VIDEO'