export const SEARCH_RESULTS_REQUEST = 'SEARCH_RESULTS_REQUEST'
export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS'
export const SEARCH_RESULTS_FAILURE = 'SEARCH_RESULTS_FAILURE'
export const SEARCH_RESULTS_SELECT = 'SEARCH_RESULTS_SELECT'
export const SEARCH_RESULTS_UNSELECT = 'SEARCH_RESULTS_UNSELECT'

export const JOBS_REQUEST = 'JOBS_REQUEST'
export const JOBS_SUCCESS = 'JOBS_SUCCESS'
export const JOBS_FAILURE = 'JOBS_FAILURE'
